services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api
        ports:
            - '3000'
        env_file: .env
        restart: always
